lang = {
    "ko-KR": {
        "nothing-Title": "아무것도 없어요",
        "nothing-Description": "(아, 옆에 먼지는 있어요)",
        "room-Title": "채팅방 만들기",
        "room-Placeholder": "방 제목 입력",
        "room-button": "확인",
        "room-Error-Short": "방 제목은 4자 이상이여야 합니다.",
        "nick-Title": "어떻게 부르면 될까요?",
        "nick-Placeholder": "닉네임 입력",
        "nick-button": "확인",
        "changeRoom-notice": "&room 방으로 변경되었습니다.",
        "block": "차단",
        "unblock": "차단해제",
        "report": "신고",
        "disconnect": "Lett 서버와의 연결이 끊겼습니다!",
        "urlconfirm": "&url\n페이지로 이동하시겠습니까?",
        "discordconfirm": "공식 디스코드 서버로 이동합니다.",
        "clearconfirm":"기록된 모든 채팅을 삭제합니다.\n삭제된 채팅은 복구할 수 없습니다.",
        "hidden": "당신만 볼 수 있습니다",
        "theme-except": "현재 dark, light 테마만 지원합니다.<br>사용법 : /theme (light / dark)",
        "e1": "이런, 당신의 눈을 보호해드리죠.",
        "unknown-command": "알 수 없는 명령어 입니다.",
        "type-text": "텍스트를 입력하세요",
        "env-setting": "사용자 설정",
        "block-list": "차단 이용자",
        "info": "정보",
        "nick-setting": "닉네임 설정",
        "notification-setting": "알림 설정",
        "lang-setting": "언어 설정",
        "theme-setting": "테마 설정",
        "developer-setting": "전문가 설정",
        "create": "생성",
        "self-input": "직접 입력",
        "recommend-input": "권장 입력"
    },
    "en-US": {
        "nothing-Title": "There is just some dust",
        "nothing-Description": "Let's start chatting",
        "room-Title": "where do you want to go",
        "room-Placeholder": "enter the room name",
        "room-button": "go",
        "room-Error-Short": "Room name must be at least 4 characters",
        "nick-Title": "Please enter your nickname",
        "nick-Placeholder": "enter nickname",
        "nick-button": "ok",
        "changeRoom-notice": "Changed room to &room",
        "block": "Block",
        "unblock": "Unblock",
        "report": "Report",
        "disconnect": "Lett server was disconnected.",
        "urlconfirm": "Redirect to &url?",
        "discordconfirm": "Redirecting to Official discord server.",
        "clearconfirm": "Delete all seeing message.\nBut u  cannot see it again.(maybe?)",
        "hidden": "only u can see XD",
        "theme-except": "We only support Light and Dark.<br>Useage : /theme (light / dark)",
        "e1": "oh shit, i can keep ur eyes from white",
        "unknown-command": "Unknown command.",
        "type-text": "Input text",
        "env-setting": "Settings",
        "block-list": "Blocked List",
        "info": "Information",
        "nick-setting": "Change nickname",
        "notification-setting": "Notification settings",
        "lang-setting": "Language settings",
        "theme-setting": "Theme settings",
        "developer-setting": "Developer settings",
        "create": "Create",
        "self-input": "Direct input",
        "recommend-input": "Recommended input"
    }
}
